print()
print("Please enter a character for the eye")
print("o")
print("Beep's expression is now as follows:")
print("\t \t \t  -######-")
print("\t \t    &/  o  o  \&")
print("\t \t     \  <-->  /")
print("\t \t \t   ------")
print("(?)#################################(?)")
print("\t \t    #          #")
print("\t \t   #        Beep#")
print("\t \t  #              #")
print("\t \t #                #")
print("\t \t ##################")
print("\t \t     (__/   \__)")