print()
print("Please enter a character for the eye")
eye = input()
print("Beep's expression is now as follows:")
print("\t \t \t  -######-")
print(f"\t \t    &/  {eye}  {eye}  \&")
print("\t \t     \  <-->  /")
print("\t \t \t   ------")
print("(?)#################################(?)")
print("\t \t    #          #")
print("\t \t   #        Beep#")
print("\t \t  #              #")
print("\t \t #                #")
print("\t \t ##################")
print("\t \t     (__/   \__)")