print("What is your name human?")
name = input()
print("\nHow old are you (in years)?")
age = int(input())
print("\nHow tall are you (in meters)?")
height = float(input())
print("\nHow much do you weigh (in kilograms)?")
weight = float(input())
print()
print(f"{name} you are {age} years old and your bmi is {weight/height**2:.2f}")
