print("Please enter the number of lives.")
lives = int(input())
print("\nPlease enter the energy level.")
energy = int(input())
print("\nplease enter the shield level.")
shield = int(input())
print("\nHealth has been set.")
print()
print(f"Lives: {'♥'*lives}")
print(f"Energy: {'♦'*energy}")
print(f"Shield: {'♦'*shield}")